// <auto-generated />
namespace DPAContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class autoIncrement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(autoIncrement));
        
        string IMigrationMetadata.Id
        {
            get { return "202103151359147_autoIncrement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
